# Basic GoReleaser configuration template
# See https://goreleaser.com for more options

project_name: testcliapp

builds:
  - id: testcliapp
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: 'testcliapp'

archives:
  - format: tar.gz
    name_template: 'testcliapp_{{.Version}}_{{.Os}}_{{.Arch}}'

release:
  name_template: 'testcliapp-{{.Version}}'
  prerelease: auto
